org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false

# Proxy settings
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.7
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=rideeverything
mod_name=RideEveryThing
mod_license=MIT
mod_version=1.9
mod_group_id=com.prizowo
mod_authors=PrizOwO
mod_description=Players can ride on any mob, including blocks, entities, and other players.
