org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.30-beta
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
mod_id=rideeverything
mod_name=RideEverything
mod_license=MIT
mod_version=1.9
mod_group_id=com.tyxcnjiu
mod_authors=LirxOwO
mod_description=Players can ride on any mob, including blocks, entities, and other players.
